#!/usr/bin/env bash
set -euo pipefail

# MangoLiquidUI — Loadstring Bundle Builder
# Reads all library .luau files, replaces require() calls, and outputs a single
# Lua file that can be loaded via loadstring(game:HttpGet("..."))()

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$SCRIPT_DIR"
OUT_DIR="$SCRIPT_DIR/dist"
OUT_FILE="$OUT_DIR/MangoLiquidUI.lua"

mkdir -p "$OUT_DIR"

# Module processing order (dependency-safe)
MODULES=(
    "Types"
    "Themes"
    "LiquidFusion"
    "RefractionProxy"
    "MangoGlassFrame"
    "MangoShimmer"
    "MangoHaptics"
    "MangoLayout"
    "MangoToggle"
    "MangoSlider"
    "MangoCheckbox"
    "MangoProgressBar"
    "MangoSegmentedControl"
    "MangoSearchBar"
    "MangoTextField"
    "MangoEnvironmentLight"
    "MangoButton"
    "MangoNotification"
    "MangoBadge"
    "MangoSkeleton"
    "MangoStepper"
    "MangoTooltip"
    "MangoToast"
    "MangoDialog"
    "MangoActionSheet"
    "MangoDropdown"
    "MangoContextMenu"
    "MangoTabBar"
    "MangoBillboardLabel"
    "MangoNotificationStack"
    "MangoBottomSheet"
    "MangoBlurProxy"
    "MangoForm"
    "MangoFocusManager"
    "MangoIntro"
    "MangoSaveManager"
    "MangoColorPicker"
    "MangoKeybind"
    "MangoCarousel"
    "MangoWindow"
    "MangoBuilder"
)

# Write header
cat > "$OUT_FILE" << 'HEADER'
-- MangoLiquidUI — Loadstring Bundle
-- Generated by build.sh — do not edit manually
-- Usage: local MangoUI = loadstring(game:HttpGet("raw_github_url"))()

local _modules = {}
local _loaded = {}
local function _require(name)
    if _loaded[name] then return _loaded[name] end
    if not _modules[name] then error("Module not found: " .. name) end
    _loaded[name] = _modules[name]()
    return _loaded[name]
end

HEADER

# Process each module
for mod in "${MODULES[@]}"; do
    FILE="$SRC_DIR/$mod.luau"
    if [ ! -f "$FILE" ]; then
        echo "WARNING: $FILE not found, skipping" >&2
        continue
    fi

    echo "_modules[\"$mod\"] = function()" >> "$OUT_FILE"

    # Read file, transform require calls, strip --!strict
    sed \
        -e 's/^--!strict$//' \
        -e 's/require(script\.Parent\.\([A-Za-z_][A-Za-z0-9_]*\))/_require("\1")/g' \
        -e 's/require(script\.\([A-Za-z_][A-Za-z0-9_]*\))/_require("\1")/g' \
        "$FILE" >> "$OUT_FILE"

    echo "" >> "$OUT_FILE"
    echo "end" >> "$OUT_FILE"
    echo "" >> "$OUT_FILE"
done

# Write footer — build and return the library table
cat >> "$OUT_FILE" << 'FOOTER'
-- Build library table
local Themes = _require("Themes")
local MangoGlassFrame = _require("MangoGlassFrame")
local RefractionProxy = _require("RefractionProxy")
local LiquidFusion = _require("LiquidFusion")
local MangoToggle = _require("MangoToggle")
local MangoSlider = _require("MangoSlider")
local MangoButton = _require("MangoButton")
local MangoBillboardLabel = _require("MangoBillboardLabel")
local MangoNotification = _require("MangoNotification")
local MangoNotificationStack = _require("MangoNotificationStack")
local MangoSegmentedControl = _require("MangoSegmentedControl")
local MangoDropdown = _require("MangoDropdown")
local MangoTabBar = _require("MangoTabBar")
local MangoSearchBar = _require("MangoSearchBar")
local MangoTextField = _require("MangoTextField")
local MangoCheckbox = _require("MangoCheckbox")
local MangoProgressBar = _require("MangoProgressBar")
local MangoDialog = _require("MangoDialog")
local MangoActionSheet = _require("MangoActionSheet")
local MangoEnvironmentLight = _require("MangoEnvironmentLight")
local MangoIntro = _require("MangoIntro")
local MangoShimmer = _require("MangoShimmer")
local MangoHaptics = _require("MangoHaptics")
local MangoLayout = _require("MangoLayout")
local MangoBadge = _require("MangoBadge")
local MangoSkeleton = _require("MangoSkeleton")
local MangoStepper = _require("MangoStepper")
local MangoTooltip = _require("MangoTooltip")
local MangoToast = _require("MangoToast")
local MangoContextMenu = _require("MangoContextMenu")
local MangoBottomSheet = _require("MangoBottomSheet")
local MangoBlurProxy = _require("MangoBlurProxy")
local MangoForm = _require("MangoForm")
local MangoFocusManager = _require("MangoFocusManager")
local MangoSaveManager = _require("MangoSaveManager")
local MangoColorPicker = _require("MangoColorPicker")
local MangoKeybind = _require("MangoKeybind")
local MangoCarousel = _require("MangoCarousel")
local MangoWindow = _require("MangoWindow")
local MangoBuilder = _require("MangoBuilder")

local MangoLiquidUI = {
    -- Full module names (backward compat)
    MangoGlassFrame = MangoGlassFrame,
    RefractionProxy = RefractionProxy,
    LiquidFusion = LiquidFusion,
    MangoToggle = MangoToggle,
    MangoSlider = MangoSlider,
    MangoButton = MangoButton,
    MangoBillboardLabel = MangoBillboardLabel,
    MangoNotification = MangoNotification,
    MangoNotificationStack = MangoNotificationStack,
    MangoSegmentedControl = MangoSegmentedControl,
    MangoDropdown = MangoDropdown,
    MangoTabBar = MangoTabBar,
    MangoSearchBar = MangoSearchBar,
    MangoTextField = MangoTextField,
    MangoCheckbox = MangoCheckbox,
    MangoProgressBar = MangoProgressBar,
    MangoDialog = MangoDialog,
    MangoActionSheet = MangoActionSheet,
    MangoEnvironmentLight = MangoEnvironmentLight,
    MangoIntro = MangoIntro,
    Themes = Themes,
    resolve = Themes.resolve,

    -- New full module names
    MangoShimmer = MangoShimmer,
    MangoHaptics = MangoHaptics,
    MangoLayout = MangoLayout,
    MangoBadge = MangoBadge,
    MangoSkeleton = MangoSkeleton,
    MangoStepper = MangoStepper,
    MangoTooltip = MangoTooltip,
    MangoToast = MangoToast,
    MangoContextMenu = MangoContextMenu,
    MangoBottomSheet = MangoBottomSheet,
    MangoBlurProxy = MangoBlurProxy,
    MangoForm = MangoForm,
    MangoFocusManager = MangoFocusManager,
    MangoSaveManager = MangoSaveManager,
    MangoColorPicker = MangoColorPicker,
    MangoKeybind = MangoKeybind,
    MangoCarousel = MangoCarousel,
    MangoWindow = MangoWindow,
    MangoBuilder = MangoBuilder,

    -- Theme shortcuts
    Light = Themes.Light,
    Dark = Themes.Dark,
    Mango = Themes.Mango,
    Mint = Themes.Mint,

    -- Intro module shortcut
    intro = MangoIntro,

    -- Haptics module shortcut
    haptic = MangoHaptics,
}

-- Existing short-name constructors
function MangoLiquidUI.bttn(config) return MangoButton.new(config) end
function MangoLiquidUI.sldr(config) return MangoSlider.new(config) end
function MangoLiquidUI.tgl(config) return MangoToggle.new(config) end
function MangoLiquidUI.chk(config) return MangoCheckbox.new(config) end
function MangoLiquidUI.dlg(config) return MangoDialog.new(config) end
function MangoLiquidUI.act(config) return MangoActionSheet.new(config) end
function MangoLiquidUI.drp(config) return MangoDropdown.new(config) end
function MangoLiquidUI.tab(config) return MangoTabBar.new(config) end
function MangoLiquidUI.srch(config) return MangoSearchBar.new(config) end
function MangoLiquidUI.txt(config) return MangoTextField.new(config) end
function MangoLiquidUI.prog(config) return MangoProgressBar.new(config) end
function MangoLiquidUI.glass(config) return MangoGlassFrame.new(config) end
function MangoLiquidUI.notif(config) return MangoNotification.new(config) end
function MangoLiquidUI.nstack(config) return MangoNotificationStack.new(config) end
function MangoLiquidUI.seg(config) return MangoSegmentedControl.new(config) end
function MangoLiquidUI.bbl(config) return MangoBillboardLabel.new(config) end
function MangoLiquidUI.env(config) return MangoEnvironmentLight.new(config) end
function MangoLiquidUI.refr(config) return RefractionProxy.new(config) end
function MangoLiquidUI.fuse(config) return LiquidFusion.new(config) end

-- New short-name constructors
function MangoLiquidUI.shimr(config) return MangoShimmer.new(config) end
function MangoLiquidUI.layout(config) return MangoLayout.new(config) end
function MangoLiquidUI.bdg(config) return MangoBadge.new(config) end
function MangoLiquidUI.skel(config) return MangoSkeleton.new(config) end
function MangoLiquidUI.step(config) return MangoStepper.new(config) end
function MangoLiquidUI.tip(config) return MangoTooltip.new(config) end
function MangoLiquidUI.toast(config) return MangoToast.new(config) end
function MangoLiquidUI.tstack(config) return MangoToast.newStack(config) end
function MangoLiquidUI.ctx(config) return MangoContextMenu.new(config) end
function MangoLiquidUI.bsheet(config) return MangoBottomSheet.new(config) end
function MangoLiquidUI.blur(config) return MangoBlurProxy.new(config) end
function MangoLiquidUI.form(config) return MangoForm.new(config) end
function MangoLiquidUI.focus(config) return MangoFocusManager.new(config) end
function MangoLiquidUI.colr(config) return MangoColorPicker.new(config) end
function MangoLiquidUI.key(config) return MangoKeybind.new(config) end
function MangoLiquidUI.carousel(config) return MangoCarousel.new(config) end
function MangoLiquidUI.csel(config) return MangoCarousel.new(config) end
function MangoLiquidUI.window(config) return MangoWindow.new(config) end
function MangoLiquidUI.build(componentType) return MangoBuilder.build(componentType) end

-- ScreenGui helper
function MangoLiquidUI.gui(name)
    local player = game:GetService("Players").LocalPlayer
    local g = Instance.new("ScreenGui")
    g.Name = name or "MangoUI"
    g.ResetOnSpawn = false
    g.IgnoreGuiInset = true
    g.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
    g.Parent = player:WaitForChild("PlayerGui")
    return g
end

-- Theme transition helper
function MangoLiquidUI.transitionTheme(glassFrames, fadeDuration, rebuildCallback)
    local TweenService = game:GetService("TweenService")
    local fadeInfo = TweenInfo.new(fadeDuration, Enum.EasingStyle.Quad, Enum.EasingDirection.Out)
    local pending = #glassFrames
    if pending == 0 then
        rebuildCallback()
        return
    end
    for _, glass in glassFrames do
        for _, shadow in glass.ShadowLayers do
            shadow.Visible = false
        end
        local tween = TweenService:Create(glass.GlassSurface, fadeInfo, { BackgroundTransparency = 1 })
        tween.Completed:Connect(function()
            pending -= 1
            if pending <= 0 then
                local newFrames = rebuildCallback()
                local fadeInInfo = TweenInfo.new(fadeDuration, Enum.EasingStyle.Quad, Enum.EasingDirection.In)
                for _, newGlass in newFrames do
                    local targetTransp = newGlass.GlassSurface.BackgroundTransparency
                    newGlass.GlassSurface.BackgroundTransparency = 1
                    TweenService:Create(newGlass.GlassSurface, fadeInInfo, { BackgroundTransparency = targetTransp }):Play()
                end
            end
        end)
        tween:Play()
    end
end

-- Auto-play intro on require
task.spawn(function()
    MangoIntro.play()
end)

return MangoLiquidUI
FOOTER

echo "Built: $OUT_FILE ($(wc -l < "$OUT_FILE") lines)"
