#!/usr/bin/env bash
set -euo pipefail

# MangoLiquidUI — Loadstring Bundle Builder
# Reads all library .luau files, replaces require() calls, and outputs a single
# Lua file that can be loaded via loadstring(game:HttpGet("..."))()

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$SCRIPT_DIR"
OUT_DIR="$SCRIPT_DIR/dist"
OUT_FILE="$OUT_DIR/MangoLiquidUI.lua"

mkdir -p "$OUT_DIR"

# Module processing order (dependency-safe)
MODULES=(
    "Types"
    "Themes"
    "LiquidFusion"
    "RefractionProxy"
    "MangoGlassFrame"
    "MangoToggle"
    "MangoSlider"
    "MangoCheckbox"
    "MangoProgressBar"
    "MangoSegmentedControl"
    "MangoSearchBar"
    "MangoTextField"
    "MangoEnvironmentLight"
    "MangoButton"
    "MangoNotification"
    "MangoDialog"
    "MangoActionSheet"
    "MangoDropdown"
    "MangoTabBar"
    "MangoBillboardLabel"
    "MangoNotificationStack"
)

# Write header
cat > "$OUT_FILE" << 'HEADER'
-- MangoLiquidUI — Loadstring Bundle
-- Generated by build.sh — do not edit manually
-- Usage: local MangoUI = loadstring(game:HttpGet("raw_github_url"))()

local _modules = {}
local _loaded = {}
local function _require(name)
    if _loaded[name] then return _loaded[name] end
    if not _modules[name] then error("Module not found: " .. name) end
    _loaded[name] = _modules[name]()
    return _loaded[name]
end

HEADER

# Process each module
for mod in "${MODULES[@]}"; do
    FILE="$SRC_DIR/$mod.luau"
    if [ ! -f "$FILE" ]; then
        echo "WARNING: $FILE not found, skipping" >&2
        continue
    fi

    echo "_modules[\"$mod\"] = function()" >> "$OUT_FILE"

    # Read file, transform require calls, strip --!strict
    sed \
        -e 's/^--!strict$//' \
        -e 's/require(script\.Parent\.\([A-Za-z_][A-Za-z0-9_]*\))/_require("\1")/g' \
        -e 's/require(script\.\([A-Za-z_][A-Za-z0-9_]*\))/_require("\1")/g' \
        "$FILE" >> "$OUT_FILE"

    echo "" >> "$OUT_FILE"
    echo "end" >> "$OUT_FILE"
    echo "" >> "$OUT_FILE"
done

# Write footer — build and return the library table
cat >> "$OUT_FILE" << 'FOOTER'
-- Build library table
local Themes = _require("Themes")
local MangoLiquidUI = {
    MangoGlassFrame = _require("MangoGlassFrame"),
    RefractionProxy = _require("RefractionProxy"),
    LiquidFusion = _require("LiquidFusion"),
    MangoToggle = _require("MangoToggle"),
    MangoSlider = _require("MangoSlider"),
    MangoButton = _require("MangoButton"),
    MangoBillboardLabel = _require("MangoBillboardLabel"),
    MangoNotification = _require("MangoNotification"),
    MangoNotificationStack = _require("MangoNotificationStack"),
    MangoSegmentedControl = _require("MangoSegmentedControl"),
    MangoDropdown = _require("MangoDropdown"),
    MangoTabBar = _require("MangoTabBar"),
    MangoSearchBar = _require("MangoSearchBar"),
    MangoTextField = _require("MangoTextField"),
    MangoCheckbox = _require("MangoCheckbox"),
    MangoProgressBar = _require("MangoProgressBar"),
    MangoDialog = _require("MangoDialog"),
    MangoActionSheet = _require("MangoActionSheet"),
    MangoEnvironmentLight = _require("MangoEnvironmentLight"),
    Themes = Themes,
    Light = Themes.Light,
    Dark = Themes.Dark,
    Mango = Themes.Mango,
    Mint = Themes.Mint,
    resolve = Themes.resolve,
}

return MangoLiquidUI
FOOTER

echo "Built: $OUT_FILE ($(wc -l < "$OUT_FILE") lines)"
